# spring.application.name=patient-service

# # PostgreSQL DataSource
# # spring.datasource.url=jdbc:postgresql://localhost:5433/db
# # spring.datasource.username=admin_user
# # spring.datasource.password=password
# # spring.datasource.driver-class-name=org.postgresql.Driver

# # spring.jpa.hibernate.ddl-auto=update
# # spring.sql.init.mode=always
# # spring.jpa.show-sql=true
# # spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# # # spring.h2.console.enabled=true
# # # spring.h2.console.settings.web-allow-others=false
# # spring.jpa.generate-ddl=true
# # spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

 
# # Kafka Producer Configuration, these properties are used to configure the Kafka producer that will send messages to a Kafka topic. The bootstrap servers property specifies the address of the Kafka broker, while the key and value serializer properties specify how the keys and values of the messages will be serialized before being sent to Kafka. 
# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer 
# spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.ByteArraySerializer


# server.port=8082
# grpc.server.port=-1

# logging.level.root=info

spring.application.name=patient-service

# --- Kafka Producer Configuration ---
# Specifies the address of the Kafka broker (using the external port we set in Docker)
spring.kafka.bootstrap-servers=localhost:9094

# Serialization (FIXED: Using the correct Apache Kafka classes)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# --- Server Configuration ---
server.port=8082
grpc.server.port=-1

logging.level.root=info