### Get All Patients
GET http://localhost:8080/api/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MjM2OTQzOCwiZXhwIjoxNzcyNDA1NDM4fQ.OPfqnuUnKdW_bufJIqiUrw7QICo9ZtCgVwwh8ZJqjpo