package com.pm.patient_management.grpc;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import com.pm.billing.BillingRequest;
import com.pm.billing.BillingResponse;
import com.pm.billing.BillingServiceGrpc;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;

// gRPC client for Billing Service to call gRPC methods exposed by Billing Service, such as getBillingInfoByPatientId, createBillingRecord, etc., to retrieve billing information for patients, create new billing records, and perform other billing-related operations as needed by the Patient Management System.
//@service annotation indicates that this class is a Spring service component, allowing it to be automatically detected and managed by the Spring container. This enables dependency injection and other Spring features to be used within this class.
@Service
public class BillingServiceGrpcClient {

    private static final Logger log = LoggerFactory.getLogger(BillingServiceGrpcClient.class);
    
    // gRPC stub for Billing Service to make synchronous/blocking calls to the Billing Service's gRPC methods. The BillingServiceGrpc.BillingServiceBlockingStub is generated by the gRPC framework based on the .proto file defining the Billing Service's gRPC API. It provides methods corresponding to the gRPC service methods defined in the .proto file, allowing the client to call those methods and receive responses from the Billing Service.
    private final BillingServiceGrpc.BillingServiceBlockingStub blockingStub;

    // Constructor to initialize the gRPC stub for Billing Service
    public BillingServiceGrpcClient(
        @Value("${billing.service.address:localhost}") String serverAddress,
        @Value("${billing.service.grpc.port:9090}") int serverPort
    )
         {

            log.info("Connecting to Billing service GRPC service at {} and port: {}", serverAddress, serverPort);

            ManagedChannel channel = ManagedChannelBuilder.forAddress(serverAddress, serverPort)
                    .usePlaintext() // Use plaintext communication (no SSL/TLS)
                    .build();

            blockingStub = BillingServiceGrpc.newBlockingStub(channel);
    }

    public BillingResponse createBillingAccount(String patientId, String name, String email) {
        // Build the gRPC request using the appropriate fields defined in your .proto file
        BillingRequest request = BillingRequest.newBuilder()
                .setPatientId(patientId) // Use the correct field name from your .proto
                .setName(name)       // Use the correct field name from your .proto
                .build();

        // Call the gRPC method and return the response
        BillingResponse response =  blockingStub.createBillingAccount(request);
        log.info("Received response from Billing service: {}", response.toString());
        return response;
    }
}
